apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ebank-discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ebank-discovery-service
  template:
    metadata:
      labels:
        app: my-ebank-discovery-service
    spec:
      containers:
        - name: my-ebank-discovery-service
          image: ouaqar/bank-account-app2-my-ebank-discovery-service:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: my-ebank-discovery-service
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: my-ebank-discovery-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ebank-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ebank-config-service
  template:
    metadata:
      labels:
        app: my-ebank-config-service
    spec:
      containers:
        - name: my-ebank-config-service
          image: ouaqar/bank-account-app2-my-ebank-config-service:latest
          ports:
            - containerPort: 9999
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://my-ebank-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 10
      # Wait for the discovery service to be ready before starting this pod
      initContainers:
        - name: wait-for-discovery
          image: appropriate/curl
          command: ['sh', '-c', 'until nc -z my-ebank-discovery-service 8761; do echo waiting for discovery service; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: my-ebank-config-service
spec:
  selector:
    app: my-ebank-config-service
  ports:
    - port: 9999
      targetPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gateway-service
  template:
    metadata:
      labels:
        app: my-gateway-service
    spec:
      containers:
        - name: my-gateway-service
          image: ouaqar/bank-account-app2-my-gateway-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://my-ebank-config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://my-ebank-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
      # Wait for the config service to be ready before starting this pod
      initContainers:
        - name: wait-for-config
          image: appropriate/curl
          command: ['sh', '-c', 'until nc -z my-ebank-config-service 9999; do echo waiting for config service; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: my-gateway-service
spec:
  selector:
    app: my-gateway-service
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-customer-service
  template:
    metadata:
      labels:
        app: my-customer-service
    spec:
      initContainers:
        - name: wait-for-discovery
          image: appropriate/curl
          command: ['sh', '-c', 'until nc -z my-ebank-discovery-service 8761; do echo waiting for eureka; sleep 2; done;']
        - name: wait-for-config
          image: appropriate/curl
          command: ['sh', '-c', 'until nc -z my-ebank-config-service 9999; do echo waiting for config service; sleep 2; done;']
      containers:
        - name: my-customer-service
          image: ouaqar/bank-account-app2-my-customer-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://my-ebank-config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://my-ebank-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: my-customer-service
spec:
  selector:
    app: my-customer-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-account-service
  template:
    metadata:
      labels:
        app: my-account-service
    spec:
      initContainers:
        - name: wait-for-config
          image: appropriate/curl
          command: ['sh', '-c', 'until nc -z my-ebank-config-service 9999; do echo waiting for config service; sleep 2; done;']
      containers:
        - name: my-account-service
          image: ouaqar/bank-account-app2-my-account-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://my-ebank-config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://my-ebank-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: my-account-service
spec:
  selector:
    app: my-account-service
  ports:
    - port: 8082
      targetPort: 8082
---